import Layout from "@/components/Layout";
import NavbarComponent from "@/components/Navbar";
import Head from "next/head";
import { useState } from "react";
import { Alert, Button, Container, Row } from "react-bootstrap";
import ListGroup from "react-bootstrap/ListGroup";
import Modal from "react-bootstrap/Modal";

export default function Home() {
  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);
  return (
    <div>
      <Layout>
        <Head>
          <title>SmartCity</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavbarComponent />

        <Container>
          <Row>
            <ListGroup>
              <Alert
                className=" d-flex justify-content-between align-items-center"
                key="primary"
                variant="primary"
              >
                Education Department Proposals
                <div className="d-flex gap-3">
                  <Button variant="info">10:12 Seconds</Button>
                  <Button variant="primary" onClick={handleShow}>
                    View
                  </Button>
                </div>
              </Alert>
              <Alert
                className=" d-flex justify-content-between align-items-center"
                key="primary"
                variant="primary"
              >
                Road and Transport Proposals
                <div className="d-flex gap-3">
                  <Button variant="info">10:12 Seconds</Button>
                  <Button variant="primary" onClick={handleShow}>
                    View
                  </Button>
                </div>
              </Alert>
              <Alert
                className=" d-flex justify-content-between align-items-center"
                key="primary"
                variant="primary"
              >
                Education Department Proposals
                <div className="d-flex gap-3">
                  <Button variant="info">10:12 Seconds</Button>
                  <Button variant="primary" onClick={handleShow}>
                    View
                  </Button>
                </div>
              </Alert>
            </ListGroup>

            {/* Proposals and result modal */}
            <Modal show={show} onHide={handleClose}>
              <Modal.Header closeButton>
                <Modal.Title>Proposals</Modal.Title>
              </Modal.Header>
              <Modal.Body>
                <ListGroup>
                  <Alert
                    className=" d-flex justify-content-between align-items-center"
                    key="warning"
                    variant="warning"
                  >
                    Build a school
                    <div className="d-flex gap-3">
                      <Button variant="danger">Vote</Button>
                    </div>
                  </Alert>
                  <Alert
                    className=" d-flex justify-content-between align-items-center"
                    key="warning"
                    variant="warning"
                  >
                    Start a bootcamp
                    <div className="d-flex gap-3">
                      <Button variant="danger">Vote</Button>
                    </div>
                  </Alert>
                </ListGroup>
              </Modal.Body>
              <Modal.Footer>
                <Button variant="primary" onClick={handleClose}>
                  Close
                </Button>
              </Modal.Footer>
            </Modal>
          </Row>
        </Container>
      </Layout>
    </div>
  );
}
